### ISSUE TITLE
Realmfirst, and PVP titles for players

### ISSUE THREAD

**Issue by sisojevic93** [AbyssWoW/BugTracker#1]
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-guides-tutorials/223957-title-ids.html

Link the titles found here with the corresponding achievement.

**Comment by AbyssWoW** [comment]
Thanks for the suggestion!

I've already done with it.

**Comment by AbyssWoW** [comment]
> Added the following Titles for the Realm First! Level 80..... achievements

**Professions:**
Grand Master Alchemist <Name> - First to 450 Alchemy
Grand Master Blacksmith <Name> - First to 450 Blacksmithing
Iron Chef <Name> - First to 450 Cooking
Grand Master Enchanter <Name> - First to 450 Enchanting
Grand Master Engineer <Name> - First to 450 Engineering
Doctor <Name> - First to 450 First Aid
Grand Master Angler <Name> - First to 450 Fishing
Grand Master Herbalist <Name> - First to 450 Herbalism
Grand Master Scribe <Name> - First to 450 Inscription
Grand Master Jewelcrafter <Name> - First to 450 Jewelcrafting
Grand Master Leatherworker <Name> - First to 450 Leatherworking
Grand Master Miner <Name> - First to 450 Mining
Grand Master Skinner <Name> - First to 450 Skinning
Grand Master Tailor <Name> - First to 450 Tailoring

**Races:**
<Name> Of Gnomeregan - First Gnome to Level 80.
<Name> Of Argus - First Draenei to Level 80.
<Name> Of Khaz Modan - First Dwarf to Level 80.
<Name> The Lion Hearted - First Human to Level 80.
<Name> Champion of Elune - First Night Elf to Level 80.

<Name> Hero of Orgrimmar - First Orc to Level 80.
<Name> Plainsrunner - First Tauren to Level 80.
<Name> Of the Darkspear - First Troll to Level 80.
<Name> The Forsaken - First Forsaken to Level 80.
<Name> Of Quel'thalas - First Blood Elf to Level 80.

**Classes:** 
<Name> of the Emerald Dream - First Druid to Level 80
Archmage <Name> - First Mage to Level 80
Assassin <Name> - First Rogue to Level 80
Crusader <Name> - First Paladin to Level 80
Prophet <Name> - First Priest to Level 80
Stalker <Name> - First Hunter to Level 80
Warbringer <Name> - First Warrior to Level 80
<Name> The Malefic - First Warlock to Level 80
<Name> Of the Ebon Blade - First Death Knight to Level 80
<Name> Of the Ten Storms - First Shaman to Level 80

**General:**
<Name> The Supreme - First player to Level 80
