### ISSUE TITLE
Quest: The Battle For Crusaders' Pinnacle

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#10]
Player : Dante , Paladin , Alliance
Location : Icecrown , 80.09 / 72.03

after completing the starter quest chain at "The Argent Vanguard" Highlord Tirion Fordring will give you the quest 

Issues: the quest requires you to post a flag (Blessed Banner of the Crusade) and protect it from attacking undead waves, Problem is the waves sometimes outright ignore the player and head straight to the flag and if that happens more then once, you will have to repeat the quest again. I did it 4 to 5 times now and it always ends up with one mob just going in and auto attacking it Also The undead mobs seems to hit like a truck for some reason.  / Sadly it is also part of the main questline in Icecrown so it's not skippable.  

Possible Fix : Make the flag more tanky ?

**Comment by Udesii** [comment]
Fixed

**Comment by NuzzyFuts** [comment]
Just tried to do this quest , the flag does not get touched. (I am okay with that)
The Player:
NuzzyFuts- Protection- 19k health
The mobs on the other hand-
Hideous Plaguebringer : "Arcing Smash" Hits for 77k 

Don't know how to get past for main quest line. 
Game has been awesome so far!
Thank you again,
Nuzzyfuts
