### ISSUE TITLE
[Quest] [Worgen] Gasping for Breath

### ISSUE THREAD

**Issue by TheRealestMcCoy** [AbyssWoW/BugTracker#108]
Quest ID 14395
Drowning Watchman ID 36440

Whats Happens Now:
Currently you can not rescue the watchmen as they can not be interacted with. This blocks the entire quest line for worgen and can not progress farther.

What Should Happen
Click on the drowning watchman he is placed on shoulder then you return in to questgiver.
Rescue 4 Drowning Watchmen.

https://www.wowhead.com/quest=14395/gasping-for-breath

**Comment by zodiuxus** [comment]
Half-working, can be clicked and gives you aura; npc doesn't jump on shoulder as they should. Will be postponed until we figure that out.
