### ISSUE TITLE
Professions 

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#11]
Player: Dante , Paladin , Alliance
![image](https://user-images.githubusercontent.com/47001800/51800216-6ee37900-2245-11e9-812c-48619b807abd.png)
i thought we get double the rates from the last update?

**Comment by Udesii** [comment]
The rates for crafting is the same 1x
Only the gathering skills (mining and herbalism) have 2x 

The 200% is the chance to gain a skills from orange recepies.
So you have a higher chance to level up your crafting skills with lower recepies
