### ISSUE TITLE
Warrior - Charge

### ISSUE THREAD

**Issue by Miidaz** [AbyssWoW/BugTracker#112]
Charge doesn't stun the target for 1.5 second as tooltip says.

**Comment by Miidaz** [comment]
This report is from our "old" BugTracker - _only merge, **not an example** for reporting an issue!_

**Comment by TheRealestMcCoy** [comment]
Charge Spell ID 100
Stun Spell ID 7922

**Comment by ghost** [comment]
Fixed #112
