### ISSUE TITLE
Sen'jin warlock trainer

### ISSUE THREAD

**Issue by Miidaz** [AbyssWoW/BugTracker#118]
Cannot train at Sen'jin warlock Trainer, gives text as if my warlock was a different class trying to talk to him.

[https://puu.sh/Ekwnb/7438540623.jpg](url)

**Comment by Miidaz** [comment]
This report is from our "old" BugTracker - _only merge, **not an example** for reporting an issue!_

**Comment by ghost** [comment]
Fixed #118
