### ISSUE TITLE
Error in realmlist.wtf form Mega download

### ISSUE THREAD

**Issue by Miidaz** [AbyssWoW/BugTracker#119]
The realmlist.wtf file has an error in it when you download from the Mega.nz link

The file reads:

set realmlist logon.abysswow.eu
set patchislt localhost

 

It SHOULD be:

set realmlist logon.abysswow.eu
set patchlist localhost

 

The error is in the word 'patchlist' and this may be cause an issue for some people.

**Comment by Miidaz** [comment]
This report is from our "old" BugTracker - _only merge, **not an example** for reporting an issue!_

**Comment by ghost** [comment]
The patchlist not needed anymore. It can be deleted from the **realmlist.wtf** file.
