### ISSUE TITLE
Honor Hold Combat Bug

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#12]
Player : Dante , Paladin , Alliance 
Location : Outlands , Hellfire Peninsula, Honor hold

Issue : in honor hold from time to time a event happens when it rains infernal balls, causing the player character to get cc'd and run around confused and it's normal until it's over but once it's over the player gets stuck in combat and can't mount or eat until he or she runs really far away from honor hold .

**Comment by Udesii** [comment]
I can't reproduce your error. After the "rain", i spent 1 min there and my "combat state" has been ended.
