### ISSUE TITLE
[Hillsbrad Foothills][Quest]Welcome to the Machine

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#120]
cannot mount the horse to give out the quests,

cant complete quest

**Comment by pottedfrog** [comment]
Quest: https://www.wowhead.com/quest=28096/welcome-to-the-machine
Horse: https://www.wowhead.com/npc=47445/skeletal-steed

Provided item - Daily Report - Hillsbrad Foothills  https://www.wowhead.com/item=62932

First Quest Dispensed  https://www.wowhead.com/npc=47444
Second Quest Dispensed https://www.wowhead.com/npc=47443
Third Quest Dispensed https://www.wowhead.com/npc=47442
