### ISSUE TITLE
[Azshara] Survey of the Lakeshore

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#124]
Using the Surveyor's Beacon item spawns the Goblin Surveyor Jr. Grade however the NPC won't interact with the Survey Equipment. This prevents the event from happening and prevents the quest from being completed. Included link to how it should be.
https://www.youtube.com/watch?v=hEbkaZSoQ8Y https://puu.sh/EkGr5/6e368d116d.jpg

**Comment by pottedfrog** [comment]
Surveyor's Beacon (Provided): https://www.wowhead.com/item=48665

Survey West Marker - co-ords 34,76 - https://www.wowhead.com/npc=35488
Survey North Marker - co-ords 34,71 - https://www.wowhead.com/npc=35487
Survey East Marker - co-ords 37,74 - https://www.wowhead.com/npc=35489

Goblin Surveyor Jr. Grade : https://www.wowhead.com/npc=35485/goblin-surveyor-jr-grade

According to some, the quest may work if you dismiss the Goblin, re-log, then re-summon him (worth a try)
