### ISSUE TITLE
Quest bugged "Fate, up against your will"

### ISSUE THREAD

**Issue by Ummlol** [AbyssWoW/BugTracker#13]
https://www.wowhead.com/quest=13369/fate-up-against-your-will
Jaina is supposed to spawn and teleport you to Orgrimmar for a diplomatic epic mission , however she does not. 

Video below of the quest working properly
https://www.youtube.com/watch?v=yXnAZZC6OTU

Picture attached of her not being WHERE SHE IS SUPPOSED TO BE
![wowscrnshot_012719_200213](https://user-images.githubusercontent.com/47087879/51805516-85ea9100-226e-11e9-8bc4-2a9f262df4c7.jpg)

Cheers
Ace

**Comment by Udesii** [comment]
Curently unavailable to go trough the scenario (will be fixed in the future).
**This quest now can be completed instantly.**

**Comment by Ummlol** [comment]
I could complete the quest but I cant complete the chain-quest.

**Comment by Udesii** [comment]
Updated the next quest aswell
