### ISSUE TITLE
[Azshara] Phased mobs attacking at Southern Ruins 

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#141]
In the screenshot to the left of the health portrait is 3 phased nagas that can attack you from different phase. Moving away far enough can see them. Included screenshot of approxmitly where they are (first) and the big map location of where.
https://puu.sh/EkU7D/4775072a02.jpg ||||| https://puu.sh/EkUaN/6bb3504f24.jpg

**Comment by ghost** [comment]
Fixed #141
