### ISSUE TITLE
Suggestion / Request 

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#15]
Player : Dante , Paladin , Alliance 

Request : To close all raids and the Icecrown 5mans down and keeping only Naxx, Ulduar and other dungeons up 

Reason : Although sure having everything open might seem like a good idea in the start but if you actually think about it, people will just skip everything and go to the ICC 5mans get all the loot from there and do ICC over and over until they get bored. and from my personal experience and others, we know that this will cause the server to die out really fast.  in hopes of keeping players interested, I suggest turning the server into a progressive server and just opening up new content slowly by time, this way you help people grow a community in the server and keeping people interested for the next raid. and due to how young the server is right now, this change won't cause the major effect to the server's players

**Comment by Udesii** [comment]
Thank you so much for your suggestion.
I'm glad to inform you, I already locked every contents above Naxx's tier, both of raids and dungeons.

You can check our content here:
https://abysswow.eu/content

**Comment by MDUnknown** [comment]
Dude you awsome :D
