### ISSUE TITLE
Bug quest in Strumgipfel

### ISSUE THREAD

**Issue by Ellynoro** [AbyssWoW/BugTracker#16]
Questname ; Das Auwärmen

Ort: Burnhildar
der Eisbär lässt sich reiten aber man kann in der Grube nicht die Npc killen die man soll

**Comment by Udesii** [comment]
You need to ride the Polar Bear, and than use your Bear's action bar to kill the Npc.
Its not bugged, I can completed it with Alliance and Horde character aswell.
