### ISSUE TITLE
Hillsbrad quest: Cry of the banshee

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#160]
Banshees from quest mirror item don't pick up wounded SI:7 agents making quest uncompletable.

**Comment by pottedfrog** [comment]
Provided Item: https://www.wowhead.com/item=64445
Banshee: https://www.wowhead.com/npc=48752
SI:7 Agents:  https://www.wowhead.com/npc=48742   &   https://www.wowhead.com/npc=48741

Have tried this quest also, Banshee attacks the Agents and kills them instead of capturing them
