### ISSUE TITLE
Quest : The Drakkensryd

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#17]
Player : Dante, Paladin, Alliance
Location : Storm Peaks, Temple of Storms 

It's one of the main questlines for the sons of Hodor Rep, the objective is simply to reach the top of the mountain and use the harpoon to jump from one dragon to another killing their riders but as a paladin or melee it's quite buggy when I land on another drake i can't melee them and 9/10 drakes I can't even hit with range abilities .

**Comment by MDUnknown** [comment]
update : i have completed the quest but after legit 1 hour of trying to find a nunbugged ones , my theory is that when you land on the drakes it makes you face the other way . thus unabling you to auto attack them

**Comment by Udesii** [comment]
The quest works properly.
When you see a huge group of Proto-Drakes, just target the nearest, and jump to them. Kill the Raider, and than just jump to another Protodrake (using your harpoon). Repeat, and you quest is done.
![wowscrnshot_012819_202932](https://user-images.githubusercontent.com/47005240/51861080-9b79bc80-233b-11e9-9d6e-fd2632730c28.jpg)
