### ISSUE TITLE
Schattenmondtal

### ISSUE THREAD

**Issue by Ellynoro** [AbyssWoW/BugTracker#18]
Quest Freundlichkeit

Gebiet Netherschwingenfelder

bitte um schnellen fix

es kommt leider kein Drache wenn ich das futter hinlege

**Comment by Udesii** [comment]
This quest works properly. Get 5x Rocknail Flayer Giblets (from Rocknail Rippers) to convert it into a Rocnkail Flyer Carcass.

Use Rocnkail Flyer Carcass, and the dragon will come and eat.
