### ISSUE TITLE
Quest Der Nebel hört nicht zu

### ISSUE THREAD

**Issue by Ellynoro** [AbyssWoW/BugTracker#19]
hallo zusammen

ich wollte einen quest bug reporten udn zwar der Nebel hört nicht zu im   Sholazarbecken

sie lassen sich nicht angreifen trotzt hasserfüllter ruf

**Comment by Udesii** [comment]
There was an error with the "frogs" faction. For now this quest can be instantly turned in. I will fix this in the future. Until that, you can complete it.
