### ISSUE TITLE
Tanaris

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#2]
Some NPCS spawn or walk on top of tents and basically get stuck there so can't kill them and can't loot the chests around them because they get aggroed

**Comment by AbyssWoW** [comment]
Thanks for your report.

Can you please submit a screenshot or npc name, to help me identify the source?

**Comment by MDUnknown** [comment]
Wastewanders NPCs mostly Wastewander Shadow Mage and their Voidwalkers

**Comment by AbyssWoW** [comment]
Thank you!

**Comment by Udesii** [comment]
Fixed
