### ISSUE TITLE
Quest : Mending Fences 

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#21]
Player: Dante , Paladin , Alliance
Location: Storm Peaks ,  East of (Dun Niffelem)
![image](https://user-images.githubusercontent.com/47001800/51937648-93e21280-2424-11e9-9b8e-a805801ea033.png)

Objective: to Kill Fjorn and 5 Stormforged Iron Giants with a help of item that requires you to grab the nearby stone and use that to summon 4 dwarfs to help you fight the Elite Giants.

Problem: dwarfs don't taunt the giants thus the player getting focused and killed. 

Note: I already completed the quest as a paladin and others have finished it.

**Comment by Udesii** [comment]
Fixed the issue. Fjorn now will fight with the dwarfs.
