### ISSUE TITLE
Quest : New Recruit 

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#23]
Player : Dante , Paladin , Alliance
Location : Icecrown 

Objective: Get an Enemy NPC ( Lithe Stalker ) to low HP and use an Item ( Sigil of the Ebon Blade ) to control them, Then bring them back to Vereth the Cunning ( Nearby ) 

Issue: when you control them they just stand in place and don't follow you back.

**Comment by Udesii** [comment]
Its not temporary fixed. Kill a Lithe Stalker and the quest can be turned in.
