### ISSUE TITLE
Quest Mounting up

### ISSUE THREAD

**Issue by TivTiv** [AbyssWoW/BugTracker#26]
Player: Tivam , Rogue Alli Location: Grizzly Hills

The Quest Mounting up ( https://www.wowhead.com/quest=12414/mounting-up ) do not work like intended. The horses reset after mounting them so you are unable to retrieve them back to Quest NPC.

**Comment by Udesii** [comment]
Fixed. You need to have more carrots in your inventory.
When its moves back, just jump off, and lure again with your quest item.
