### ISSUE TITLE
Time lost protodrake do not move.

### ISSUE THREAD

**Issue by TivTiv** [AbyssWoW/BugTracker#29]
Name: Tivam   Location: Stormpeaks 

The NPC Time Lost Protodrake ( do i really have to link him?) do not move. He/she should fly his/her path.
The NPC Vyragosa have the same issue.

**Comment by Udesii** [comment]
Fixed. TLPD now "teleports" to a new location at every 25 secs. (not fly, she teleports now)

If its killed, respawn time: 24 hours

Good hunting!
