### ISSUE TITLE
Paladin Blessing of Might

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#3]
There seems to be a visual bug in the amount of attack power increase between how much you actually get compared to what it says when you mouse over it. 
![image](https://user-images.githubusercontent.com/47001800/51723579-1197ce00-2073-11e9-97be-48917486e830.png)
![image](https://user-images.githubusercontent.com/47001800/51723621-3c822200-2073-11e9-8ceb-0f3a433541ee.png)
It seems to only be a visual bug and I'm getting the correct amount of AP added into my stats But I might be wrong.

**Comment by Udesii** [comment]
You need to Delete your Cache folder, and check again. This issue can't reproduced at my side.

**Comment by Udesii** [comment]
Please after the Cache delete, check again. I waiting for your reply

**Comment by MDUnknown** [comment]
i just checked it and it's still there my theory is that it involves the Ret Talent " [Improved Blessing of Might]"

**Comment by MDUnknown** [comment]
yap the talent adds 25% extra AP to the buff but that isn't added into the buff description when you mouse over it but it still adds up to your Actual AP stat so it's working right but this might cause some confusion in the future for newer players

**Comment by Udesii** [comment]
Thank you for your reply. I checked it again, and this only shows you (for less ap shown). For the party, group members don't get your +AP from your talent. Anyways I will do something with this report in the future.

**Comment by MDUnknown** [comment]
fair enough ^^
