### ISSUE TITLE
Feralas quests

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#309]
quest: Ysondre's Call- NPC missing from Emerald Summit so not completeable.                                                                                    quest: Rescue OOX-22/FE! Escort quest auto completes.
quest: The Gordunni Orb- Gordunni Warlocks and Shaman's don't drop orb so quest uncompleteable.
quest: Still with the zapped giants- Zorbin's Ultra shrinker doesn't work so quest uncompleteable.
quest: Dark Heart- Horn of Hatetalon does not spawn Edana Hatetalon so quest not completeable.
quest: Sealing the dream- Ysondre's Tear does nothing at the portal so unable to seal portal so quest not completeable.
quest: Might of the Stonemaul- No mobs in the arena so quest not completeable.

**Comment by coniecit** [comment]
[The Gordunni Orb] - Feralas

I confirm that the Orb doesn't drop, so the quest cannot be completed
