### ISSUE TITLE
Quest : No Place to Run

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#31]
Player : Dante , Paladin , Alliance
Location : Dragonblight 

Objective : Place ward and protect it from attacking waves while it gains power 

Issue : once it's powered up fully, it vanishes and doesn't complete the quest
![image](https://user-images.githubusercontent.com/47001800/52144052-93d95100-2676-11e9-8a5e-415bd9c991f5.png)
Read the chat

**Comment by Udesii** [comment]
Fixed.
When the last waves every mob killed, the quest is completed.
