### ISSUE TITLE
Boss : Pyroguard Emberseer

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#33]
Player :  Dante 
Location : Blackrock Spire (Dungeon)
NPCs : https://www.wowhead.com/npc=9816/pyroguard-emberseer / 

Issue : When you enter the room for the boss, the casters there instantly attack you instead of just being busy casting on the boss. making the player unable to do it normally and kill them by using the alter in the room  in order for the boss to be attackable , Thus bugging the room making the player unable to progress in the Dungeon ( this is extra annoying due to the fact you need to clear this place to get to Blackwing lair for mogging ! ) 
![image](https://user-images.githubusercontent.com/47001800/52165527-74e0ca80-271b-11e9-993b-43b3f2d4ba3e.png)

and I'm sure the alter could be soloed in wotlk .

**Comment by Udesii** [comment]
Its fixed. Now you need to wait 5 mins (after used the Altar), and the boss will get his empovered buff, and the fight starts.
