### ISSUE TITLE
[H][Swamp of Sorrows] We Are Under Attack!

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#347]
Probably players are in wrong phase or no phase at all. Enemies should invade Stonard.
https://www.wowhead.com/quest=27857/were-under-attack

**Comment by coniecit** [comment]
Confirmed. Affects the following 2 alliance quests as well:
- [Cutting Supply] (no supplies to loot)
- [Assault on Stonard] (no Stonard Defenders to kill in the area)
