### ISSUE TITLE
Boss : High Justice Grimstone

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#36]
Player: Dante 
Location: Burning Steps, Blackrock Depths ( Dungeon )
NPC: https://www.wowhead.com/npc=10096/high-justice-grimstone

Objective: The boss walks around the arena opening gates and you have to kill whatever comes out from the gates 

Issue: Boss opened one Gate, we killed everything then he vanished and no other gate opened. and we basically ware stuck there, unable to go back or forward because all gates ware shut.

**Comment by Udesii** [comment]
Fixed. Kill the beasts from the cages, kill the "Champion", than push forward.
