### ISSUE TITLE
[H][Hellfire Peninsula] Burn It Up... For the Horde!

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#374]
https://www.wowhead.com/item=27479 can't be used at given location.
https://www.wowhead.com/quest=10087/burn-it-up-for-the-horde

**Comment by pottedfrog** [comment]
Western Cannon Location : 55,53 Hellfire Peninsula
Eastern Cannon Location : 60,51 Hellfire Peninsula
