### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Lemonadez** [AbyssWoW/BugTracker#38]
Do you guys allowed Zygor Guide?
I know certain server dont allowed it due to their anti-cheat. 
As Zygor guide does request on server between the character for complete / incomplete quest. 

i am using warmane client + same addon that ive been using on that server. 

So I ask gm to install zygor and see if you get ban by your anti-cheat, before me and my friends start playing.

ty

**Comment by Udesii** [comment]
Share a link, and we will check it out.

**Comment by Udesii** [comment]
Will check out when I can.
