### ISSUE TITLE
Quest : Into the Realm of Shadows

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#39]
Player : Dante (alt Death) 
Location : Death knight starting zone

Objective : Go into the shadow realm and kill " Dark Rider of Acherus" and ride his horse " Acherus Deathcharger '' back 

Issue : the overall horse npc is weird when you try to bring him back he justs starts walking back to his spawn randomly even going through the mountain to reach it lol, I got off him and suddenly I have super speed while running? i felt like i was hacking lol and it kept happening for a while and the only way to gain control of the horse is to spam dismount and mount him again .

**Comment by Udesii** [comment]
Every "horse tame" quest works this way. It means the horse fighting against your will.

The movement speed is a bug I will fix it shortly.
