### ISSUE TITLE
Rars dont drop green items

### ISSUE THREAD

**Issue by Ellynoro** [AbyssWoW/BugTracker#4]
In the dark coast and the marshes the rars will not drop any green items

**Comment by Udesii** [comment]
Its need a little more information:
- Creature name, which not drops the "greens".

When you provide this, I will look after the issue.

**Comment by Ellynoro** [comment]
all rars in this area... i have kills 4 rars and no green items

**Comment by Udesii** [comment]
Please provide a full area name, where you met this issue. It will help me to find the creatures missing drops.

Note: If you can tell, only one creature name it will also help a lot.

**Comment by TivTiv** [comment]
Can confirm. Most rares should drop greens. Killed some rars in different zones but got not a single drop. Need to check more of them and try to provide the english names for you.

**Comment by Udesii** [comment]
Whats needed, is the zone name, where you've met this issue
Plus if you can, the rare creature's name.

From the server side, theres 11,653 rare creature, and all of them have their own loot pool. When you provide some additional informations, I be able to fix the issue with the tomorrows major update.

**Comment by Udesii** [comment]
Updated 19 Rare NPCs. For the correct fix, please tell me the creatures name.

**Comment by Udesii** [comment]
When someone encounter this issue (no rare creature drops), please provide the creature name, and I will fix it.

**Comment by Ellynoro** [comment]
close pls ty
