### ISSUE TITLE
Spell : Dancing Rune Weapon 

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#40]
Player : Dante ( alt Death ) 

Issue : Dancing Rune Weapon isn't working 

![image](https://user-images.githubusercontent.com/47001800/52220974-895ac980-28b9-11e9-99a7-538469d2572d.png)

**Comment by Udesii** [comment]
Not summon the sword or its not do any dmg? Please give mode informations

**Comment by MDUnknown** [comment]
Does not deal damage at all . nor does it use the same attacks as me .

**Comment by Udesii** [comment]
I close this issue, but it can be found here: https://github.com/AbyssWoW/BugTracker/issues/56
