### ISSUE TITLE
Wotlk Dungeons

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#41]
Player: Dante, Paladin, Alliance
Party Members: ( Dante / Twix / Tivam / Miau / Ace / Draynn / Debulis / Avora / Perfectz / Bjorn / Zastotocky )

Objective: Do all Dungeons in all Normal and HC to find out bugs and report them here. 

### Dungeons : - 
**Utgarde Keep ( Not Tested )**
**Utgarde Pinnacle ( Not Tested )**
- Note:  3rd boss / Phase 1 disable, untill its fixed by @Udesii 
 
**The Nexus ( Completed in HC )**
- Minor Issue: caster mobs when silenced don't run towards the player ( they stand still ) 

**The Oculus ( Completed in HC )**
- Minor issue: caster mobs when silenced don't run towards the player ( they stand still ) 

**Azjol-Nerub ( Completed )**

**Ahn'kahet ( Completed )**

**Gundrak ( Completed in HC )**

**Drak'Tharon Keep ( Completed in HC )**
- Minor issue : Trash mods ( Risen deathknights ) before the last boss might be a bit overtuned.
 
**The Violet Hold ( Completed in HC )**
- Note: Door was removed.
- Minor issue: NPC Azure Sorceror ( https://www.wowhead.com/npc=30667/azure-sorceror#abilities ) Seems to be spamming his knockback ability, especially annoying when there is more than one spamming it, melee can't get close. 
 
**Halls of Stone ( Not Tested )**

**Halls of Lightning ( Completed )**

**The Culling of Stratholme ( CLOSED )**
- Major issue: Arthas RP is Broken. // This Dungeon is temporarily disabled until the fix goes LIVE. by: @Udesii 

**General Bugs: -**
- Trash in Hc doesn't seem to drop loot ( only gold ) 
 

Note:  we will Test more and keep this list updated!

**Comment by Udesii** [comment]
Fixed the Door issue for The Violet Hold.

- Culling of Stratholme currently unable to enter, untill the fix goes live.

**Comment by Udesii** [comment]
Utgarde Pinnacle: Fixed
- Removed Gruf from Skadi, now its instantly starts phase 2. Gruf will added back when its fixed.

**Comment by Udesii** [comment]
The Nexus 4th Boss Adds fixed.

Previously: * Major issue: 4th boss (Ormorok the Tree-Shaper) has NPCs stuck in his arena forcing the party to face the trash pack and him at the same time.

Now, they are outside of the "fighting circle"
