### ISSUE TITLE
EPL [Warchief's Command: Eastern Plaguelands!]

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#414]
NPC Missing, can't turn in the quest.

**Comment by coniecit** [comment]
Same goes for the Alliance version of the quest, [Hero's Call: Eastern Plaguelands!]. NPC is missing

https://youtu.be/q1g5puQ3b6M?t=508

**Comment by coniecit** [comment]
Also, same problem with quests [Visitors] and [Into The Woods]
