### ISSUE TITLE
Floating vendor

### ISSUE THREAD

**Issue by Gitteroo** [AbyssWoW/BugTracker#42]
Kira songshine, The traveling vendor between stormwind and goldshire, floats most of the way to gold shire
![wowscrnshot_020619_115040](https://user-images.githubusercontent.com/47398056/52366087-20349c80-2a06-11e9-84a7-636d786f0959.jpg)

**Comment by MDUnknown** [comment]
maybe she just drank redbull.

**Comment by Udesii** [comment]
Fixed
