### ISSUE TITLE
Quest : Escape from Silverbrook 

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#45]
Player: Dante 
Location: Grizzly Hills 
Quest: https://www.wowhead.com/quest=12308/escape-from-silverbrook

Objective: Free the prisoner and help him escape by both of you riding on a horse and fighting off werewolves ( it is fun ) 

Issue: we reached the location and he just stands there not moving or anything so I can't finish the quest
![image](https://user-images.githubusercontent.com/47001800/52415809-7df9df00-2b01-11e9-998d-9deac9e14d31.png)
![image](https://user-images.githubusercontent.com/47001800/52415827-894d0a80-2b01-11e9-9f69-f1efb4f32235.png)

**Comment by Udesii** [comment]
Fixed. The quest can be completed, when you kill your the worgen pursuiter.
