### ISSUE TITLE
Quest : Mounting up

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#46]
Player: Dante
Location: Grizzly Hills 
Quest: https://www.wowhead.com/quest=12414/mounting-up

Objective: Gather carrots from the field nearby and use it on wild horses to mount them and bring 5 back to the base

Issue: once you mount the horse and take to far off his spawn area , he just starts automatically walking back to his spawn making you unable to drag any horse back to the camp.

**Comment by Udesii** [comment]
Its already fixed.

Every mount tame or capture quests works in this way, cus they fighting against your will.

More info: https://github.com/AbyssWoW/BugTracker/issues/26
