### ISSUE TITLE
Quest : If Valgarde Falls

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#47]
Player: Dante 
Location: the Howling Fjord 
Quest: https://www.wowhead.com/quest=11243/if-valgarde-falls

Objective: kill 12 Dragonflayer Invaders or Dragonflayer Worgs

Issue: Low number of both NPCs spawning, I would suggest reducing the spawn time for them.

**Comment by Udesii** [comment]
Fixed
