### ISSUE TITLE
"An End To All Things..." GAMEBREAKING DK BUG

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#479]
The Lich King is supposed to offer you this quest and you would be only a few quests away from finishing DK starting zone, but he is just standing there staring in the distance.  "The Scarlet Apocalypse" the pre-quest was normally completed but for some reason Lich King is not offering you this quest and you can not complete DK zone without it and you can't leave the zone either.
https://www.wowhead.com/quest=12779/an-end-to-all-things

**Comment by ghost** [comment]
Fixed case id #479
