### ISSUE TITLE
Quest: Return of the High Chief

### ISSUE THREAD

**Issue by spgranger** [AbyssWoW/BugTracker#48]
Player: Broadus
Location: Dragonblight
Quest: Return of the High Chief
Issue: After using the Anub'ar Prison Key to release Roanauk Icemist as the first part of the quest, he left the prison but then bugged out and the rest of the quest did not fire.  The expectation is that Roanauk would call down Under-King Anub-et-kan, but instead Roanauk Icemist is standing in place next to the prison.  I dropped the quest, logged out for an hour, and picked the quest back up yet he was still standing in place in the same place when I went to complete the quest again.  He is still standing there at this time.

**Comment by Udesii** [comment]
Fixed, need to kill Under-King Anub'et'kan, than loot the q item.
