### ISSUE TITLE
 [How To Win Friends And Influence Enemies] H, DK Starting Zone

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#480]
Cannot be completed no matter how long are you beating the mobs with the quest items, no dialogue is happening thus this quest cannot be completed. 
https://www.wowhead.com/quest=12720/how-to-win-friends-and-influence-enemies

**Comment by ghost** [comment]
Fixed case #480

**Comment by coniecit** [comment]
I've been hitting mobs with both https://www.wowhead.com/item=39371/keleseths-persuader equipped in the quest area for the last 20 mins, but quest won't complete (character name: Veggy)
