### ISSUE TITLE
Paladin Talent (Sacred Duty)

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#491]
The talent is suppose to show a buff time stamped to show what the buff should be like

It doesn't work at all no buff nothing I have 2 points into it which is 50% chance to proc and haven't seen the proc ever also 1/2 talent doesn't work. The talent is suppose to make shield of the righteous 100% crit when procced by judgement and/or Avenger's shield.

**Comment by ghost** [comment]
Fixed #491
