### ISSUE TITLE
Paladin hand of reckoning

### ISSUE THREAD

**Issue by Cauthrien** [AbyssWoW/BugTracker#5]
It is not doing any damage

**Comment by Udesii** [comment]
`"Taunts the target to attacks you. If the target is tauntable and not currently targeting you, causes X holy damage."`

This means, when you playing with your friend, and he/she aggroed the target, and fighting with it, when you use your **Hand of Reckoning**, you will deal damage to it, plus generate 500% aggro.

The damage not "included", or "dealed" when you are the only target for that creature.
