### ISSUE TITLE
Quest: Honor Challenge

### ISSUE THREAD

**Issue by spgranger** [AbyssWoW/BugTracker#51]
Player: Broadus
Location: Icecrown
Quest: Honor Challenge
Issue: The expected behavior for this quest is that once you use the "Challenge Flag" quest item on a Mjordin Combatant, you may then engage the mob, and once it is defeated it will count toward the 6 Mjordin Combatants challenged and defeated needed to complete the quest.  At the moment doing so does not cause your count to go up, meaning that it is currently impossible to complete the quest.

**Comment by MDUnknown** [comment]
weird, I did this quest the other day didn't have issues with it?

**Comment by spgranger** [comment]
Alright, so I just went back to check it out again, and the first one I
tried worked, but then the next 3 I tried after did not work again.  I'm
doing the same thing on each- deploying the challenge flag near them and
not pulling until I see the "challenged" debuff on them, but sometimes it
works and sometimes it doesn't.

**Comment by spgranger** [comment]
I was just able to complete the quest- it took 2 or 3 times longer than it
probably should have because more than half of the time it didn't work, but
it's probably not a super high priority.

**Comment by Udesii** [comment]
Its works as intended. You need to drop the flag to the combatant, than the NPC got the flags "buff". Kill them, and you're done.
