### ISSUE TITLE
[H][Borean Tundra] Neutralizing the Cauldrons

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#517]
Can't use item near the cauldrons.
https://www.wowhead.com/quest=11647

**Comment by pottedfrog** [comment]
Cauldron : https://www.wowhead.com/npc=25490/east-enkilah-cauldron
Cauldron : https://www.wowhead.com/npc=25493/west-enkilah-cauldron
Cauldron : https://www.wowhead.com/npc=25492/central-enkilah-cauldron

Item given : https://www.wowhead.com/item=34806
