### ISSUE TITLE
priest raid buff 

### ISSUE THREAD

**Issue by evilwc** [AbyssWoW/BugTracker#52]
"Prayer of Fortitude" and "Prayer of Spirit" wont effent party members

**Comment by Udesii** [comment]
Sadly, every party/raid buffs has this issue. I'm working on them, but untill I fix this issue, you need to manually add the (targetable ones) to every players. Its a known issue, and should be fixed.

**Comment by Udesii** [comment]
I close this, but its can be found at our pinned: Known Issues post

**Comment by Udesii** [comment]
Fixed
