### ISSUE TITLE
 [H][Dragonblight] A Fall from Grace

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#523]
Couldn't complete it, can't remember details.
https://www.wowhead.com/quest=12274/a-fall-from-grace

**Comment by pottedfrog** [comment]
Can't talk to final NPC to complete this quest - he is currently tagged as aggressive, with no option to interact (he doesn't attack or move even though flagged as such for client)

Quest part 1 : https://www.wowhead.com/npc=27445
NPC : https://www.wowhead.com/npc=27444
