### ISSUE TITLE
 [H][Dragonblight] The Denouncement

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#525]
Nothing happens when using the quest item on the NPCs. Can't denounce them.
https://www.wowhead.com/quest=12273/the-denouncement

**Comment by pottedfrog** [comment]
Item provided : https://www.wowhead.com/item=37438

NPCs : 
https://www.wowhead.com/npc=27426
https://www.wowhead.com/npc=27427
https://www.wowhead.com/npc=27428
https://www.wowhead.com/npc=27429
