### ISSUE TITLE
[H][Dragonblight] Mystery of the Infinite

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#529]
Couldn't place the quest item on the ground within the area.
https://www.wowhead.com/quest=12470

**Comment by pottedfrog** [comment]
Quest: https://www.wowhead.com/quest=12470/mystery-of-the-infinite
Hourglass: https://www.wowhead.com/item=37923
Bronze Dragonshrine is at 71,38, Dragonblight
