### ISSUE TITLE
Quest: Battle for Crusader's pinnacle

### ISSUE THREAD

**Issue by NuzzyFuts** [AbyssWoW/BugTracker#53]
still figuring this site out.  
Just tried to do this quest again ,
this is a repost-
 the flag does not get touched. (I am okay with that)
The Player:
NuzzyFuts- Protection- 19k health
The mobs on the other hand-
Hideous Plaguebringer : "Arcing Smash" Hits for 77k

Don't know how to get past, for main IC quest line.
Game has been awesome so far!
Thank you again,
Nuzzyfuts

**Comment by Udesii** [comment]
Fixed
Reduced the damage dealt by Hideous Plaguebringer's Arcing Smash. Avaregare damage now between 8k-16k
