### ISSUE TITLE
Transmog : [Ashbringer + essense]

### ISSUE THREAD

**Issue by Shadowlessbg** [AbyssWoW/BugTracker#54]
i get my ashbringer cant transmog it. 
![image](https://user-images.githubusercontent.com/47495599/52532450-0f4d9900-2d2e-11e9-89c0-3764e40d8c0e.png)

**Comment by Udesii** [comment]
Only the same type weapons and armors can be transmogrified. Two-Hand sword to Two-Hand sword and so on. You can find more informations about this at https://abysswow.eu/faq or at our discord server #faq page.

Quote from our FAQ:

> Q: How can I use the Transmog system?
A: The Transmog system is almost the same as the retail one, but with some additional changes. Please check out our How to Use Transmog System Rules below:
The character must be able to equip both items.
Common (White), Uncommon (Green), Rare (Blue), Epic (Purple) and some Legendary (Orange - Only legos from Vanilla and TBC) items may be transmogrified.
Heirlooms and Account Bound items can be transmogrified.
Heirlooms and Account Bound items can be used to transmogrify.
Only the selected items modell/skin moved, your stats and set bonuses are not affected.
Items must share the same armor type (examples: plate for plate, cloth for cloth).
Weapons must be the same weapon type (exceptions: Guns, Crossbows, or Bows) so, you ONLY ABLE to transmogrify your Two-Handed Sword, into another Two-Handed Sword (you can't use Axe or Polearm as a Sword). This function is the major difference compared to the retail version.
Main hand weapons can only be used to transmogrify Main hand weapons.
Off-hand weapons can only be used to transmogrify Off-hand weapons.
One handed weapons can be used to transmogrify a Main hand or Off-hand weapon.
Using an item for transmogrify makes it soulbound. An item that was still tradable with other eligible players (raid loot and the likes) will of course also no longer be tradable.
Using an item for transmogrify makes it non-refundable.
Fishing Poles cannot be transmogrified.
Fishing Poles cannot be used to transmogrify.
Vendoring an item strips its transmogrification.
The displayed enchant will be that of the currently equipped item.
There may be individual items that are excluded from being transmogrified on the basis that they were originally added to the game as absurdities. (examples: a weapon that looks like a fish, or a chest piece that is invisible…)

**Comment by Shadowlessbg** [comment]
[image: image.png]

На нд, 10.02.2019 г. в 13:10 ч. Udesii <notifications@github.com> написа:
