### ISSUE TITLE
[H][Sholazar Basin] The Mist Isn't Listening

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#545]
Quest related creatures in the area can't be attacked, giving error Invalid Target.
https://www.wowhead.com/quest=12538

**Comment by pottedfrog** [comment]
Mobs that can't be attacked even though they are flagged as aggressive : 

Mistwhisper Warrior : https://www.wowhead.com/npc=28109
Mistwhisper Oracle : https://www.wowhead.com/npc=28110
