### ISSUE TITLE
Quest N1 : Gluttonous Lurkers

### ISSUE THREAD

**Issue by Shadowlessbg** [AbyssWoW/BugTracker#55]
The rat dont drop quest item / zul drak /  . by Shadowless 
![image](https://user-images.githubusercontent.com/47495599/52532701-dfa09000-2d31-11e9-8081-949b705a5d9d.png)

**Comment by Udesii** [comment]
Added the quest item to the Lurking Basilisk, and the rats now have the conjure table aswell, but higher chance to get the quest item is from the Basilisks.
