### ISSUE TITLE
[Elune's Gifts] - Desolace

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#550]
When visited, the locations do not trigger objective completion
https://youtu.be/grL4ZzfK0Ng?t=48

**Comment by pottedfrog** [comment]
Quest: https://www.wowhead.com/quest=14354/elunes-gifts

Quest parts:
Handmaiden Of Elune Visited - co-ords 76.34 26.08, Desolace Phase0 - https://www.wowhead.com/object=195517
Elune's Brazier Visited - co-ords 78.45 22.60, Desolace Phase0 - https://www.wowhead.com/object=195497
Cup of Elune Visited - co-ords 76.70 18.60, Desolace Phase0 - https://www.wowhead.com/object=195438
