### ISSUE TITLE
[Lifting the Siege] - Dustwallow Marsh

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#561]
Using Paxton's Torch doesn't progress the quest 
https://youtu.be/QbV4adil0-E?t=25

**Comment by pottedfrog** [comment]
Quest: https://www.wowhead.com/quest=24948/lifting-the-siege
Torch : https://www.wowhead.com/item=52017

Quest stages:
Rageroar Catapults Burned (x3) :  https://www.wowhead.com/npc=38818
Rageroar Blade Thrower Burned : https://www.wowhead.com/npc=38820

Catapults located near 68:38 Southern Barrens
Thrower is near 68:37 Southern Barrens
