### ISSUE TITLE
 [Working the Bugs Out] - Southern Barrens

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#565]
Bucket of Burning Pitch doesn't work
https://youtu.be/WDmZsWAGuBg?t=35

**Comment by pottedfrog** [comment]
Quest: https://www.wowhead.com/quest=25082/working-the-bugs-out
Item: https://www.wowhead.com/item=50128
NPC to kill (spawns when item used on mounds) : https://www.wowhead.com/npc=3252 

Silithid mounds approx co-ords: 47:67 and 48:68.
