### ISSUE TITLE
 [A Line in the Dirt] - Southern Barrens

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#566]
When clicking the banner, nothing happens

**Comment by pottedfrog** [comment]
As no side is stated, have listed both versions

**H version** : https://www.wowhead.com/quest=24546/a-line-in-the-dirt
Point Captured : https://www.wowhead.com/npc=37667
Point Defended : https://www.wowhead.com/npc=37668


**A version** : https://www.wowhead.com/quest=25045/a-line-in-the-dirt
Hill Captured : https://www.wowhead.com/npc=39029
Hill Defended : https://www.wowhead.com/npc=39030
