### ISSUE TITLE
Quest : It Goes to 11...

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#57]
Player: Dante ( Death ) 
Location: Howling Fjord, Nifflevar
Quest: https://www.wowhead.com/quest=11421/it-goes-to-11

Objective: Go into Nifflevar and use the harpoon weapons to destroy some buildings and kill some NPCs

Issue: Missing Harpoons or the given item(Harpoon Control Mechanism) doesn't work on actual harpoons around.
![image](https://user-images.githubusercontent.com/47001800/52535109-eba54580-2d63-11e9-9063-7cb4a29e6fb4.png)

**Comment by Udesii** [comment]
Temporary fixed.
To complete this quest, you need to kill 8 of the Dragonflayer Defenders.
