### ISSUE TITLE
[Diplomacy By Another Means] - Southern Barrens

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#570]
Horn of Challenge doesn't work inside the Bristleback Challenge Ring

**Comment by pottedfrog** [comment]
Ally version : https://www.wowhead.com/quest=25044/diplomacy-by-another-means
Horn : https://www.wowhead.com/item=49782
Sabersnout: https://www.wowhead.com/npc=37513 - spawn co-ords 43, 41.8

Bristleback Challenge Ring is at 43,42 - Southern Barrens
