### ISSUE TITLE
Lost in the Floods Quest broken

### ISSUE THREAD

**Issue by zodIIac** [AbyssWoW/BugTracker#577]
Thonk's Spyglass does not work on top of the tower.

**Comment by pottedfrog** [comment]
Quest: https://www.wowhead.com/quest=25187/lost-in-the-floods
Thonk's Spyglass: https://www.wowhead.com/item=52514

Quest parts : 
Find Raggaran - https://www.wowhead.com/npc=39357
Find flooded hut - https://www.wowhead.com/npc=39358
Find Misha - https://www.wowhead.com/npc=39359
Find Zen'Taji - https://www.wowhead.com/npc=39360

NPC you use the spyglass next to - co-ords 49.6, 40.0, Durotar Phase 0 - https://www.wowhead.com/quest=25227/thonk

1 cinematic to watch per 'find' part
