### ISSUE TITLE
Quest :  The Ransacked Caravan

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#58]
Player: Dante 
Location: Howling Fjord
Quest: https://www.wowhead.com/quest=11465/the-ransacked-caravan

Objective: Use the falcon to grab turkeys in the area 

Issue: When Falcon brings back the Turkey it doesn't count towards the progress of the quest making it impossible to complete.

**Comment by Udesii** [comment]
Fixed. When you kill a turkey, its drops the quest item.
