### ISSUE TITLE
Invalid report - please use a specific title for it.

### ISSUE THREAD

**Issue by sigmis** [AbyssWoW/BugTracker#584]
I may be over shooting but 100% of the object based quests aren't able to be completed. Quests like "Through Fire and Flames" (freeing wolves by clicking their post) and "Missing in Action" (clicking on cages to open gnomes and free them) don't work. "Into the Raptor's Den" (placing a feather in a nest) doesn't work either.

The gnome quest is important as it's part of the starting questline and gnomes can't go further.

**Comment by ghost** [comment]
Invalid report.
Use a specific title for your report, attach links (wowhead) and an exact quest names, and dont use some attention/eye-catcher title. Won't get much mkre attention from us.
Please use the pinned guide aswell for getting an examples with issue reporting.

**Comment by zodIIac** [comment]
General LQ, no updates. Closed.
