### ISSUE TITLE
Feathermoon Stronghold Boat bridge (Feralas)

### ISSUE THREAD

**Issue by coniecit** [AbyssWoW/BugTracker#585]
The Feathermoon Stronghold bridge that helps access the boat is missing 

https://i.imgur.com/nHQhiPD.jpg

**Comment by ghost** [comment]
This bridge is related to a quest or?

**Comment by coniecit** [comment]
No, it's not related to a quest. It's just a general bug. The bridge is there so that you can access the boat and get to the Ruins of Feathermoon Island instead of swimming for 5 mins.

**Comment by ghost** [comment]
Thanks for provide a proper informations about this case.
We will investigate it.

**Comment by zodIIac** [comment]
Been looking for the bridge for you to add.. Then googled for 5mins:
https://wowwiki.fandom.com/wiki/Feathermoon_Ferry
Please whatever you post, PROVIDE SOURCE WITH LINKS!

**Comment by TheRealestMcCoy** [comment]
The boat and bridge is gone in cata. It was destroyed during the Cataclysm. Hints why there is a new Feathermoon and the old one is now called the ruins. There should be a quest that does lead you to the ruins but it should take you via a transport. Once there you can talk to the worgen to return.

https://www.wowhead.com/quest=25304/the-battle-of-sardor is the quest that takes you to the ruins Via the tree guy
https://www.youtube.com/watch?v=qfFoIV4mNxg
