### ISSUE TITLE
quest: Battle for Crusaders' Pinnacle

### ISSUE THREAD

**Issue by NuzzyFuts** [AbyssWoW/BugTracker#59]

**Comment by NuzzyFuts** [comment]
Didn't mean to leave empty disc above ><

Went to do the quest.
Arcing smashed - Fixed 
Mob named:
Reanimated Captain- Melee (non-crit) 15.7k damage 

Do not know melee swing speed or if this mob is suppose to hit that hard. 
Thank you again,
Nuzzy

**Comment by Udesii** [comment]
That need to hit hard, but I will check out tomorrow

**Comment by Udesii** [comment]
Reanimated Captain's damage has been nerfed by 30%.

**Comment by NuzzyFuts** [comment]
Still unsure about this one. Do believe it is a solo-able quest. Going to try with healer friend and see. Will post results when completed.

Nuzzy

**Comment by NuzzyFuts** [comment]
Completed , solo . 
Had to go ret
