### ISSUE TITLE
Quest : Falcon Versus Hawk

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#60]
Player: Dante / Death 
Location: Howling Fjord
Quest: https://www.wowhead.com/quest=11468/falcon-versus-hawk

Objective: Use the falcon to catch/kill Hawks

Issue: the same issue with #58 / the falcon goes and comes back and I still don't get credited.

**Comment by Udesii** [comment]
Fixed. You can find the quest item in the Hawks.
