### ISSUE TITLE
[Break The Unbreakable] - Felwood (Quest)

### ISSUE THREAD

**Issue by coniecit** [AbyssWoW/BugTracker#603]
The Claw of Tichondrius doesn't dispel the flame barrier when used

https://youtu.be/Wd-TXukgUUU?t=36

**Comment by pottedfrog** [comment]
Quest: https://www.wowhead.com/quest=28113/break-the-unbreakable
Item: https://www.wowhead.com/item=63031
Wall co-ords : 36, 65 (roughly)
