### ISSUE TITLE
[Gameobjects] Missing portals in Shattrath

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#607]
The portals to Orgrimmar and Stormwind are missing from Shattrath.

As per Patch 4.1.0 (https://wow.gamepedia.com/Patch_4.1.0) - quote: "Portals to each of the capital cities have returned to Dalaran and Shattrath City"

IGN : Slimline

**Comment by zodIIac** [comment]
SW portal was here, added the missing OG portal.
