### ISSUE TITLE
Paladin Bug

### ISSUE THREAD

**Issue by coniecit** [AbyssWoW/BugTracker#616]
Divine Shield and Hand of Protection don't cast the Forbearance debuff on the Paladin. 
Both spells should cast Forbearance when used.

**Comment by ghost** [comment]
Fixed #616
Additional note:
- Hand of Protection is not suggested to give a player a Forbearance debuff (Tooltip).
![image](https://user-images.githubusercontent.com/47005240/66287356-bdb5d800-e8d5-11e9-8090-8d9ac4b16a82.png)
I don't find any references for the debuff.

**Comment by coniecit** [comment]
https://i.imgur.com/l9gwP0D.jpg and also https://cata-twinhead.twinstar.cz/?spell=1022

**Comment by ghost** [comment]
Forbearance Debuff also added for the spell: **Hand of Protection**
