### ISSUE TITLE
Blood Red Key (drop) - Felwood

### ISSUE THREAD

**Issue by coniecit** [AbyssWoW/BugTracker#617]
Right clicking on the Blood Red Key doesn't work in order to get the quest

**Comment by zodIIac** [comment]
Please dig up a source to confirm the item should still start the questchain. I could only find a comment saying that as of 4.0.3 its DEPRECATED.

**Comment by pottedfrog** [comment]
I can confirm that as of 4.0.3a the quest chain was removed : https://wow.gamepedia.com/Blood_Red_Key - the item itself (https://www.wowhead.com/item=13140/blood-red-key) should no longer drop - that is the bug in this case.

**Comment by ghost** [comment]
This item now removed from the database.
Case closed #617
