### ISSUE TITLE
Quest : Lightning Infused Relics 

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#62]
Player: Death / Dante 
Location: Howling Fjord
Quest: https://www.wowhead.com/quest=11494/lightning-infused-relics
Quest: https://www.wowhead.com/quest=11495/the-delicate-sound-of-thunder

Objective: Use the robot suit and walk around the mining site to find crystals, use the special robot suit Bottens to zap the crystals for information / Get inside one of the caves inside to find a Loken statue and listen to what Loken has to say to complete the quest

Issue: Gathering information from the crystals don't give credit to the quest / The event aka the speech from Token isn't triggering.  Both quests are unable to be completed.

**Comment by Udesii** [comment]
Fixed.
**Quest: Lightning Infused Relics** - instantly completed, since theres some missing scripting. WIll working in the future.
**Quest: The Delicate Sound of Thunder** - fixed, now triggered and can be completed.
Extra video:
