### ISSUE TITLE
<Skinning> Sawtooth Crocolisks cannot be skinned

### ISSUE THREAD

**Issue by coniecit** [AbyssWoW/BugTracker#622]
Sawtooth Crocolisks in Swamp of Sorrows should be skinnable

**Comment by zodIIac** [comment]
PLEASE! Include a wowhead for the NPC next time, searching the IDs takeng me longar than fixing the skinloot. Much appreciated.

**Comment by coniecit** [comment]
Sorry, wasn't checking my emails regarding these entries. Will include a wowhead from now on
