### ISSUE TITLE
[Curtail the Darktail] - Blasted Lands (Quest)

### ISSUE THREAD

**Issue by coniecit** [AbyssWoW/BugTracker#626]
Using the quest item (https://www.wowhead.com/item=57119/enohars-explosive-arrows) on the quest mobs (https://www.wowhead.com/npc=42235/darktail-bonepicker) has no effect

https://youtu.be/C3aDt3PYvh4?t=47

**Comment by pottedfrog** [comment]
Quest : https://www.wowhead.com/quest=25709/curtail-the-darktail
Enohar's Explosive Arrow : https://www.wowhead.com/item=57119
Darktail Bonepicker: https://www.wowhead.com/npc=42235

Just noticed the video isn't your proof of the quest not working, it's a 3yr old video of the working quest.
