### ISSUE TITLE
[The Amulet of Grol] - Blasted Lands (Quest)

### ISSUE THREAD

**Issue by coniecit** [AbyssWoW/BugTracker#627]
Clicking on the pile of skulls doesn't spawn the required NPC https://classic.wowhead.com/npc=7665/grol-the-destroyer

https://youtu.be/ITUPOhzi34Q?t=118

**Comment by pottedfrog** [comment]
Ally Quest: https://www.wowhead.com/quest=26169/the-amulet-of-grol

The amulet (https://www.wowhead.com/item=10753) doesn't drop from the skull pile (co-ords 70.89 35.49 - https://www.wowhead.com/object=203230/head-of-grol), it is looted from the mob - Spirit of Grol (https://www.wowhead.com/npc=41267/spirit-of-grol) that spawns.

Just noticed the video isn't your proof of the quest not working, it's a 3yr old video of the working quest.
