### ISSUE TITLE
[The Amulet of Sevine] - Blasted Lands (Quest)

### ISSUE THREAD

**Issue by coniecit** [AbyssWoW/BugTracker#628]
The quest NPC (https://www.wowhead.com/npc=41265/salt-flop) is missing the required dialogue option

https://youtu.be/DUnu99Y1GA0?t=53

**Comment by pottedfrog** [comment]
Ally version : https://www.wowhead.com/quest=26168/the-amulet-of-sevine

The quest NPC Kasim Sharim (https://www.wowhead.com/npc=42298/kasim-sharim) is missing the after hand-in text.

Completion:
"`<Kasim hefts the amulet.>`

A warlock... and a powerful one at that.  I will hold onto this until the time is right."
