### ISSUE TITLE
Magic Carpet Ride Quest

### ISSUE THREAD

**Issue by Anura93** [AbyssWoW/BugTracker#63]
Miközben visz le a szőnyeg a partra. Át repülünk Kel'thuzad felett rám agrozik és 2 hitel így meg nem adja be a küldit

**Comment by Udesii** [comment]
Fixed. Nerfed the damage dealt by Kel'Thuzad at Borean Thundra by: 70%

**Comment by pottedfrog** [comment]
Whilst doing the same quest today, I was 2 shot my Kel'thuzad , https://puu.sh/EqM6k/c23b31e53d.png

Maybe this is related to issue #653 ?
