### ISSUE TITLE
Grey item drop rates need tweaking

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#630]
Mobs seem to be dropping excessive amounts of grey items although the issue isn't tied in to a specific mob or item. Some kills below with loot screenshot results per set.

**First Set**
Screenshot of 3 drops, loot drops are seperated by my simple . comment in chat.
1st kill is Mire Hydra : https://www.wowhead.com/npc=18213/mire-hydra
2nd and 3rd kills are Umbrafen Eel : https://www.wowhead.com/npc=18138/umbrafen-eel
Loot Screenshot : https://puu.sh/Eptnw/7d88c0750d.png

**Second Set**
2 kills of Umbraglow Stinger : https://www.wowhead.com/npc=18132/umbraglow-stinger
Loot Screenshot : https://puu.sh/Eptrz/4e30dcac4e.png

**Third Set**
1st kill is Umbrafen Witchdoctor : https://www.wowhead.com/npc=20115/umbrafen-witchdoctor
2nd kill is Umbrafen Oracle : https://www.wowhead.com/npc=18077/umbrafen-oracle
3rd kill is rare Bog Lurker : https://www.wowhead.com/npc=18682/bog-lurker
Loot Screenshot : https://puu.sh/Eptyi/0094057b3d.png

**Fourth Set**
3 kills of Illidari Taskmaster : https://www.wowhead.com/npc=17058/illidari-taskmaster
Loot Screenshot : https://puu.sh/EptJm/209726e98e.png

Total drops from 11 kills: 
20x grey items
5x green items
3x blue items
9x white items
Various coin drops from humanoids as expected
Quest drops not included in the count

**Comment by zodIIac** [comment]
Its a complex issue we are awere of. Under investigation.
Could you tell when did this start approximately?

**Comment by pottedfrog** [comment]
I noticed an increase in grey loot drops approx 2-3 days ago, but wanted to be sure it wasn't just a couple of mobs here and there, or simple random chance that was causing it, before I brought up the issue.

Maybe something changed / didn't save in one of the tables that control drop chances ? *shrug*

As an addition to the above mobs - Bog Lords, Withered Bog Lords & Starving Bog Lords to name just some more from what I remember - also have the same issue.

I did a test earlier and was able to get an average gold income of approx 1.6-1.9k /hr at level 64 (tested for 30 minutes with 60 empty bag spaces). Considering that 90% of the items I had dropped were grey, that's a silly high gold/hr rate at that level ...

**Comment by ghost** [comment]
What about the drop now, it feels better?

**Comment by pottedfrog** [comment]
Much better overall now, RNG being what it is you still sometimes get 2-3 grey drops from a mob, or double up blues, but now I'm not running to town every 10 minutes or less.

With the current rates across the board (grey,white,green etc), it feels more fluid for questing, crafters will now be useful, and making money, although still faster than blizz, is now at a much more sedate pace in the lower levels, rather than the 1-2k per hour it was possible to do before this was fixed. ;) 

If I notice anything unusal whilst chewing the quests I'll report back.
