### ISSUE TITLE
In-game date is out of line with Calendar

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#631]
1) DMF should have spawned at Thunder Bluff yesterday, still no sign of it
Outside TB :  https://puu.sh/EpEnq/8a49de21eb.png
Calendar : https://puu.sh/EpEpo/81bd1eecdb.png

2) At the time of writing, Midsummer Fire tents are around various towns in Outland - Thrallmar and Shattrath (https://puu.sh/EpERI/c01aa8cf2c.png) I've seen so far.
2a) If it was Midsummer Festival, DMF should still spawn outside TB : https://puu.sh/EpEt5/e2ab7cb163.png

3) Pilgrim's Bounty is being advertised by Goblin Commoners in Shattrath : https://puu.sh/EpEOC/79f5137c13.png

IGN : Slimline

**Comment by zodIIac** [comment]
I'll have a look. Please edit if you come across anything related.
