### ISSUE TITLE
[Quest][Daily] Escargot A Go-Go

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#632]
This quest (https://www.wowhead.com/quest=29333/escargot-a-go-go worked until at least 2 days ago, it has now come around again, but whenyou click the snails (https://www.wowhead.com/item=69918) to pick them up you get no credit for them, they simply vanish.

Proof it worked, as I have the achievement for the UC Cooking : https://puu.sh/EpELa/0408abc709.png

IGN : slimline

**Comment by ghost** [comment]
Fixed #632
