### ISSUE TITLE
[Beta realm] PvP Mode doesn't disable

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#633]
Even when turned off, PvP mode still stays enabled after the 5 minutes of non-pvp:
5min countdown: https://puu.sh/EpRaQ/de3328f525.png
After: https://puu.sh/EpR4D/0985042409.png

**Comment by ghost** [comment]
Invalid. Beta-Realm is PVP based. If you turn-off your flag, it only affect your character at your faction controlled zone, capital cities and sanctuaries.
Open world (like Tanaros for example - any zones which contested), the PVP cannot turned off.

**Comment by pottedfrog** [comment]
As that is the case, the bug should be that PvP mode doesn't auto-enable once you leave your faction safe zones - I ran through all of Eastern Kingdoms and Kalimdor without PvP flagging.

Will test for Outland now - currently flying to Shattrath to turn off pvp and then check if it turns on once I enter Terokkar Forest.

**Comment by pottedfrog** [comment]
Well everything seems tobe working fine now - no idea why I managed to go round without pvp first time, but I can't reproduce. Closing issue,
