### ISSUE TITLE
[Gameobject] Hearthstone changes to 'jail isle' in Dustwallow Marsh

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#637]
When you get put into combat with the 'slime' type creatures in Dustwallow Marsh, your Hearthstone gets changed to Warchief's Lookout - there is no way off if you hearth out after this happens other than a GM summoning you.

The creatures that cause this issue are around the crashed zeppelin site area, namely : 
Acidic Swamp Ooze: https://www.wowhead.com/npc=4393
Bubbling Swamp Ooze: https://www.wowhead.com/npc=4394

The HS reset happens whether or not you get hit or attacked - 2-3s after being put into combat you get a noise then the message 'Warchief's Lookout is now your home.'

**Comment by ghost** [comment]
Provide a character name and one of us for rescue you.

**Comment by pottedfrog** [comment]
I am not trapped there, I didn't use the hs - members of the guild first noticed this a while ago but it took some testing to find out what was the actual cause.

**Comment by zodIIac** [comment]
Its fixed on dev.
