### ISSUE TITLE
[Not Just Any Body] - Blasted Lands (Quest)

### ISSUE THREAD

**Issue by coniecit** [AbyssWoW/BugTracker#638]
https://cata-twinhead.twinstar.cz/?object=203204 which contains https://cata-twinhead.twinstar.cz/?item=55829 is missing from 46,26 spot, therefore the quest can't be completed

https://youtu.be/udPCk4MN6jk?t=67

**Comment by zodIIac** [comment]
Please refrain from using any other database sites other than wowhead.com . These may use custom and/or different IDs than ours thus providing false or inappropiate info. Just like in this case.
https://www.wowhead.com/object=203204/dreadmaul-cache  As you can see it has 3 locations not just one.

**Comment by zodIIac** [comment]
In the future please refrain from using any other database sites than wowhead as these may provide false or non Blizzlike info.

**Comment by coniecit** [comment]
The only reason I used a different database was because I could not find the specific item on Wowhead.
