### ISSUE TITLE
[NPC] Daggerfen Assassin not targettable

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#642]
Whilst doing the quest Wanted: Chieftain Mummaki (https://www.wowhead.com/quest=10117/wanted-chieftain-mummaki) I found that the Daggerfen Assassin (https://www.wowhead.com/npc=18116/daggerfen-assassin)at the top of the tower are untouchable and unkillable. Pet on defensive simply stands still and dies to them.

They have no name plates showing either: https://puu.sh/Eqbns/b95f0c5de3.png

Daggerfen Assassin on the ground around the tower have no nameplates, but CAN be killed if you manually click to target each one: https://puu.sh/Eqbrs/41e481aa6e.png

**Comment by zodIIac** [comment]
Added stealth to the assassin mobs.
