### ISSUE TITLE
[Quest][Daily][Fishing]A Golden Opportunity (new issue)

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#646]
Follow on from issue #142 : 
As at time of writing, unable to test the fix from Changelog #4 

Quest : https://www.wowhead.com/quest=26572/a-golden-opportunity

New issue: 
Razgar's Fillet Knife (https://www.wowhead.com/item=58955) no longer given when accepting quest.

**Comment by ghost** [comment]
You are able to complete this quest by killing the Gold Fish (than loot it).

**Comment by pottedfrog** [comment]
Thanks, didn't attempt it as I didn't get the knife :) Will try it when I get to Org.

**Comment by pottedfrog** [comment]
Tested and working in its' current state.

**Comment by zodIIac** [comment]
A-ha.... So I just spent some time fixing the stupid spell not to kill the player. I expect you @Miidaz to put that item back and make it Blizz now that the spell is working.

**Comment by ghost** [comment]
When we fix the spell, the item will re-added to the quest.
