### ISSUE TITLE
[NPC]R-3D0 is in the 'dead' position

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#654]
The R-3D0 (https://www.wowhead.com/npc=21690/r-3d0) shows as being 'dead' -  it should be stood upright.

Location is 55.0, 72.8 Blade's Edge Mountains

**Comment by zodIIac** [comment]
Invalid. See video
https://www.wowhead.com/quest=10580/where-did-those-darn-gnomes-go#videos:id=57320
