### ISSUE TITLE
[Quest]A Race Against Time

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#656]
As per #581, the grenade still **does not** allow you to attack Inquisitor Salrand : https://puu.sh/EqXti/6fb580998f.png - bottom right (looks like a smoke flare) is the grenade.

Text from Salrand is correct after you 'take off' the shield : https://puu.sh/EqXw1/fa5ff43032.png

Error : Invalid target is spammed on screen, pet dies to him without retaliating - threw the grenade 4 times before I had to feign to avoid being killed.

Quest does not work as it should, sequence should be: 
1) Goto Beryl Shield wall area
2) Throw Grenade to bring down Salrand from his spot
3) Inquisitor Salrand whines about being disturbed
4) He comes down from his 'floating' spot and you fight
5) Kill him, loot his box to get key

There should not be any Beryl Mage Hunters inside the blue wall area (there are 3 that spawn there currently), and Salrand should not come down to join the fight until the grenade has been used.

Quest : https://www.wowhead.com/quest=11671/a-race-against-time
Item : https://www.wowhead.com/item=34897
Salrand : https://wotlk.wowhead.com/?npc=25584
Box :https://www.wowhead.com/object=187875/salrands-lockbox
Broken key : https://www.wowhead.com/item=34909

**Comment by ghost** [comment]
Working without issues.
Reference (recorded at 11th of October 2019 13:12 CEST - link: https://streamable.com/sla18)

Invalid report #656
