### ISSUE TITLE
Essence of Luck

### ISSUE THREAD

**Issue by BjornTheTree** [AbyssWoW/BugTracker#66]
The issue: Essence of Luck is soulbound.

What makes this an issue is that classes that are really good at farming have the upperhand.
For example healers will have a way harder time farming Essence of luck.

My solution would be to make them Account-bound. It will not change anything in the end except that you can choose which character on your account you will get cosmetics for.

* Bjorn/Babybjorn

**Comment by Udesii** [comment]
Fixed.
The Essence of Luck's quality changed to Binds to Account.
The Essence of Luck has now the following description: 
> This item is a special currency, for Landro Longshot.
Landro Longshot sell a Lootbox, and some Vanity Toys, Pets and Mounts from the Loot Box.

Landro Longshot can be found at Stormwind City, Orgrimmar and Dalaran.
