### ISSUE TITLE
[Gameobjects] Tua'kea's Crab Traps - mutliple spawns on same spot

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#661]
For the quest https://www.wowhead.com/quest=12009/tuakeas-crab-traps the traps (https://www.wowhead.com/item=35802) are spawning on top of each other - in some cases there are up to 3 at the exact same location.

**Comment by ghost** [comment]
Can't repruduce this issue. MArked as invalid until the OPs reply.

**Comment by pottedfrog** [comment]
I've seen this multi-spawn of objects on top of each other in a few places in the entire world. I completed this quest at only 3 trap spots -at the spots it only shows 1 trap, but when you click it, you can instantly click the other(s) one at a time in the same place.

It's either a multi-spawn point, or an insta-respawn at the same spot - either of which should not happen :)

**Comment by ghost** [comment]
Checked at DB, and ingame aswell. I can't find any instant "respawn", nor multiple spawns on the same location.
Closing this now.
