### ISSUE TITLE
[Quest] The arts of a warlock

### ISSUE THREAD

**Issue by z3nos** [AbyssWoW/BugTracker#672]
The quest The Arts of a Warlock does not progress by using Immolate on the Tiki targets.

Wowhead link contains the use of corruption
**https://www.wowhead.com/quest=26274/the-arts-of-a-warlock**

Here a Twinstarlink that showcases the use of immolate
https://cata-twinhead.twinstar.cz/?quest=26274

**Comment by ghost** [comment]
Fixed #672
