### ISSUE TITLE
[Quest] Warchief's Command: Silverpine Forest!

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#690]
This quest (https://www.wowhead.com/quest=26964/warchiefs-command-silverpine-forest) is missing from Executor Zygand (https://www.wowhead.com/npc=1515).

Have done all pre-quests in the chain and I am now level 11 (should be available from level 9)

**Comment by ghost** [comment]
After completing every pre-quest, I was able to pick up the suggested quest "Warchief's Command: Silverpine Forest!" from  Executor Zygand at level 9.

The quest opened up after completing the following quest:
Take to the Skies (https://www.wowhead.com/quest=25012/take-to-the-skies)

**Comment by pottedfrog** [comment]
As per the comments on the quest page, you don't need to complete the chain to get this quest.

It's also one that is available any time from level 9  - as long as you don't do any quests in Silverpine (which I haven't)

Wholly (addon) quests still remaining in Tirisfal Glades, highlighted details on this quest, no pre-quest listed : https://puu.sh/EsWV2/b9ea518014.png

No quest, no talk option: https://puu.sh/EsWWX/db0b5075b8.png
