### ISSUE TITLE
Request :-)

### ISSUE THREAD

**Issue by Ellynoro** [AbyssWoW/BugTracker#7]
hi I again, I have a request for the professions that it is a little easier alone herbalism is pretty annoying, maybe the rates increase slightly or something?

**Comment by Udesii** [comment]
With the next major update (January 26th - tomorrow), it will be implemented to the game.
You can find more informations about this at our discord server.
https://discordapp.com/invite/VQYHVsb

**Comment by Ellynoro** [comment]
ok ty
