### ISSUE TITLE
[Quest] (80) If he cannot be turned. Vile goes down too quick

### ISSUE THREAD

**Issue by DrArkaneX** [AbyssWoW/BugTracker#72]
Vile goes down in like 3 hits.  I know this can be done, but Vile needs to be able to tank better than that... :)

**Comment by DrArkaneX** [comment]
Vile only spawns with 10k HP.  I'm not sure on retail what he is supposed to spawn with

**Comment by DrArkaneX** [comment]
wowhead reports he has 10k health but is an Elite classification.  I would suppose he has some enormous amount of armor to be able to withstand more than 3 hits from lightsbane

**Comment by Udesii** [comment]
Fixed. Vile's Armor, and Damage has been increased. Now, he not goes down too quick.
