### ISSUE TITLE
[Q] Icecrown

### ISSUE THREAD

**Issue by tmsb-gh** [AbyssWoW/BugTracker#74]
https://www.wowhead.com/quest=13388
I think after we blow the bombs, we should be dropped down or knocked down. I had to fly down on my own.

I've had a hard time turning/getting these quests in/from the NPC, experienced heavy phasing issues in the area.
https://www.wowhead.com/quest=13389/a-short-fuse
https://www.wowhead.com/quest=13390
However, the next quest in the chain had no phasing issues:
https://www.wowhead.com/quest=13391

Hope this helps. Contact Sacryn if  additional info is needed.

**Comment by Udesii** [comment]
After the "Set it Off!" (https://www.wowhead.com/quest=13388), you need to jump to the hole, and complete A Short Fuse (https://www.wowhead.com/quest=13389/a-short-fuse).

Talk with the Crystal, than a Boy (https://www.wowhead.com/quest=13390/a-voice-in-the-dark).
Kill the Monsters (https://www.wowhead.com/quest=13391/time-to-hide) and use the portal to go back to surface, and go back to the Ship.

Fixed the phasing issue, while the player do the "Set it Off!" (https://www.wowhead.com/quest=13388) quest.
