### ISSUE TITLE
Overspawn

### ISSUE THREAD

**Issue by Ellynoro** [AbyssWoW/BugTracker#76]
Charname: Blacktank

Problem: it is an overspawn of Truesilver Ore, there are hardly any other ores present (Mithril Ore) or Thorium ore.

I ask for a fix and adjustments

here are a few more pages

https://www.wowhead.com/object=2040/mithril-deposit
https://www.wowhead.com/object=2040/mithril-deposit

**Comment by tmsb-gh** [comment]
I do agree with the first part, Truesilver is common spawn. But, there are plenty of Mithril and Thorium nodes. Especially Thorium - A LOT of nodes. Mining can be easily leveled, just takes time and you have to go to the right zone.

**Comment by Udesii** [comment]
Fixed.
Now, Truesilver Veins have a pool, where its spawns on different places, BUT theres a 5-16% chance to respawn again somewhere, and override some other Nodes.
