### ISSUE TITLE
[NPC] Nozzlepot

### ISSUE THREAD

**Issue by pottedfrog** [AbyssWoW/BugTracker#771]
There are SIX Nozzlepots at Nozzlepot's Outpost in Northern Barrens

1 by the inn
2 at each of the 2 entrances to the fence compound
1 wandering around the small area

https://puu.sh/ExE5Z/29d5596ace.png

**Comment by pottedfrog** [comment]
with abyss_world as selected db:


SET @id_to_delete = 34698;

DELETE FROM creature
    USING creature
    WHERE creature.id = @id_to_delete;

INSERT INTO `abyss_world`.`creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseId`, `phaseGroup`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES ('137611', '34698', '1', '0', '0', '1', '0', '0', '0', '0', '1117.81', '-3356.16', '92.5502', '4.97176', '500', '0', '0', '386', '0', '2', '0', '0', '0', '0');


This will remove the 5 stationary ones and keep the walker.

**Comment by ghost** [comment]
Fixed with the provided code.
#771
