### ISSUE TITLE
size scalling of Hunter pets dont work

### ISSUE THREAD

**Issue by Ellynoro** [AbyssWoW/BugTracker#78]
size scalling of Hunter pets dont work

my t rex is little, my rhino again

![wowscrnshot_021819_145934](https://user-images.githubusercontent.com/47025500/52955872-1dcf2c80-338e-11e9-8d7b-ecfc98c7e421.jpg)

**Comment by Udesii** [comment]
Fixed, in the future some other pets size should be increased in the future.
PTR capture: https://streamable.com/f2jf6

**Comment by Ellynoro** [comment]
no fix for my dino and my cats
