### ISSUE TITLE
Quests - Icecrown

### ISSUE THREAD

**Issue by tmsb-gh** [AbyssWoW/BugTracker#81]
https://www.wowhead.com/quest=13380/leading-the-charge
https://www.wowhead.com/quest=13381/watts-my-target
https://www.wowhead.com/quest=13404/static-shock-troops-the-bombardment

All the quests above are bugged. Players should talk to https://www.wowhead.com/npc=31648/karen-no to put you in a bomber. She has a Gossip that wafter clicked puts a buff on you, but the bomber (vehicle) does not arrive.

Here is a link for the quest. Bad quality tho. https://www.youtube.com/watch?v=nnJMLBD4oHs

**Comment by Udesii** [comment]
+1 Quest has been added: https://www.wowhead.com/quest=13382/putting-the-hertz-the-valley-of-lost-hope

Fixed. Since the bomber is missing from the core script, these quests can be now instantly completed.
