### ISSUE TITLE
QUEST : Scourge Tactics

### ISSUE THREAD

**Issue by MDUnknown** [AbyssWoW/BugTracker#9]
Player: Dante, Paladin, Alliance 
Location: Icecrown, The Argent Vanguard 

The quest needs me to free 8 webbed crusaders but the webbed NPCs have a too long respawn time, because I only found 4 and I been flying around for almost 30+ minutes and non spawned. 
![106879-scourge-tactics](https://user-images.githubusercontent.com/47001800/51792584-9cd8a700-21cc-11e9-8880-b580f810bee0.jpg) This is the Webbed NPC and the quest requires 8.  + it's not a skippable quest if you looking to progress down the Icecrown main questline

**Comment by MDUnknown** [comment]
and it's not a skippable quest if you want to progress into Icecrown questlines.

**Comment by Udesii** [comment]
Fixed
