### ISSUE TITLE
Wotlk Raids

### ISSUE THREAD

**Issue by BjornTheTree** [AbyssWoW/BugTracker#95]
Major thread for all bugs and issues in the wotlk raids
(Feel free to add anything)

Player: Bjorn/Babybjorn
Discord: Saintified

### **Naxxramas:**

**Raidwide:**

**Anub'Rekhan**
https://www.wowhead.com/npc=15956/anubrekhan

Fell through the floor and we had to run outside to reset the dungeon,

**Noth the Plaguebringer**
https://www.wowhead.com/npc=15954/noth-the-plaguebringer#abilities:mode=n25

Major issue: Script is broken.
First phase worked well, he spawned skeletons. 
He then used teleport, NPC did appear on the balcony but he was stuck on the ledge of the balcony, dialogue didn't start. 
The skeletons spawned during the balcony phase.
After the balcony phase, he never teleported back and the boss fight/script was stuck.

### **Vault of archavon:**
https://www.wowhead.com/npc=31125/archavon-the-stone-watcher

**Archavon the Stone Watcher:**

Major issue: Resets back to full hp. From either LoS or the jump. Something made him evade and reset.
Could have been the xfaction raid.

### _____________________

this is an open thread so feel free to add on to it. 
If you see anything that is wrong or can add more information please do.
I think we all want it to work flawlessly! 
Thank you guys
 
Bjorn

**Comment by Ellynoro** [comment]
no trash loot too

**Comment by tmsb-gh** [comment]
We got trashloots yesterday and today too.
